version: '3'

services:

  backend:
    build: .
    container_name: backend
    volumes:
      - .:/home/node/app
    command: ["npm","run","start:dev"]
    ports:
      - 3000:3000
    
  db:
    image: mysql:latest
    container_name: db_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=gabriel
      - MYSQL_PASSWORD=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=nest

  php_my_admin:
    image: phpmyadmin:latest
    environment:
      - PMA_USER=root
      - PMA_HOST=db_mysql
    ports:
      - 8080:80